import ImageKit from "imagekit";
import { env } from "../config/env.js";
import { serviceUnavailable } from "../utils/errors.js";

let client: ImageKit | null = null;

export function imageKitConfigured(): boolean {
  return Boolean(env.IMAGE_KIT_END_POINT && env.IMAGE_KIT_PUBLIC_KEY && env.IMAGE_KIT_PRIVATE_KEY);
}

export function imagekit(): ImageKit {
  if (!imageKitConfigured()) throw serviceUnavailable("Image uploads are not configured on this server");
  if (!client) {
    client = new ImageKit({
      urlEndpoint: env.IMAGE_KIT_END_POINT!,
      publicKey: env.IMAGE_KIT_PUBLIC_KEY!,
      privateKey: env.IMAGE_KIT_PRIVATE_KEY!,
    });
  }
  return client;
}

/** Builds the public URL for a stored ImageKit path. */
export function imageUrl(filePath: string): string {
  if (/^https?:\/\//.test(filePath)) return filePath;
  const base = (env.IMAGE_KIT_END_POINT ?? "").replace(/\/$/, "");
  return `${base}/${filePath.replace(/^\//, "")}`;
}

/** Downloads an image and returns it as base64 for the model. */
export async function fetchImageAsBase64(filePath: string, fallbackMime = "image/png"): Promise<{ mimeType: string; data: string }> {
  const res = await fetch(imageUrl(filePath), { signal: AbortSignal.timeout(15_000) });
  if (!res.ok) throw new Error(`Could not download image (${res.status})`);
  const mimeType = res.headers.get("content-type")?.split(";")[0] || fallbackMime;
  const buf = Buffer.from(await res.arrayBuffer());
  return { mimeType, data: buf.toString("base64") };
}

/** Uploads a base64 image (for example generated by the model) and returns its path. */
export async function uploadBase64(data: string, fileName: string, folder = "/koala-ai/generated"): Promise<{ filePath: string; url: string }> {
  const res = await imagekit().upload({ file: data, fileName, folder, useUniqueFileName: true });
  return { filePath: res.filePath, url: res.url };
}
